### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by DarkmatterVale**
- Update HTML documentation
- Add README.md

### CODE REVIEW

**Comment by DarkmatterVale** [comment]
This closes https://github.com/HaikuArchives/Dynamate/issues/7

Link to GCI task: https://codein.withgoogle.com/dashboard/task-instances/6000796806152192/

**Comment by pulkomandy** [comment]
Hi,

I think it would be better to include the CSS instead of hosting it on cloudflare. Otherwise, the doc cannot be viewed offline (and the files will be included in releases).

There are a few changes that can be made:
- The license mentionned in the files is not correct anymore (now Dynamate is under the MIT license)
- The broken links to acc.umu.se can be removed. If relevant, link to http://audjoo.com/old/software/dynamate/ instead (this is the current home of Dynamate for non-Haiku platforms).

**Comment by DarkmatterVale** [comment]
Is that all you would like me to update?

**Comment by DarkmatterVale** [comment]
@pulkomandy I do not think it is relevant to include the link to http://audjoo.com/old/software/dynamate/ because it is also out of date ( and this is for Haiku, not other platforms ). Is it alright if I just say the code is being maintained on Github by the Haiku community?

**Comment by DarkmatterVale** [comment]
@pulkomandy I have cleaned up the documentation. Does it look better now?

**Pull request merged**
